// Level generator + prover for HUNDO.
//
//   node tools/generate.mjs
//
// Composes 100 chapters from the segment library, then PROVES each one is
// beatable by searching the actual game simulation for a working tap
// sequence. Chapters that can't be solved get regenerated easier until they
// can. Writes js/levels.js and tools/solutions.json (tap scripts, used by the
// browser replay tests).

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { WORLDS, composeChapter, solve, replayWins, minTaps } from './generate_lib.mjs';

const __dir = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------- main
const levels = [];
const solutions = [];
let totalTaps = 0;

for (let w = 0; w < 10; w++) {
  for (let ci = 0; ci < 10; ci++) {
    const n = w * 10 + ci + 1;
    let def = null, bits = null;
    for (let attempt = 0; attempt < 30 && !bits; attempt++) {
      const drop = Math.floor(attempt / 6);
      def = composeChapter(w, ci, n * 1000 + attempt * 7 + 13, drop);
      bits = solve(def);
      if (bits && !replayWins(def, bits)) {
        console.error(`ch${n}: replay mismatch, retrying`);
        bits = null;
      }
      if (bits && attempt < 12) {
        const t = bits.reduce((a, c, i) => a + (c && !bits[i - 1] ? 1 : 0), 0);
        if (t < minTaps(def.verb, def.segs)) bits = null;   // too free, recompose
      }
      if (!bits && attempt >= 29) {
        console.error(`ch${n}: UNSOLVABLE after retries`);
        process.exit(1);
      }
    }
    const taps = bits.reduce((a, c, i) => a + (c && !bits[i - 1] ? 1 : 0), 0);
    totalTaps += taps;
    levels.push(def);
    solutions.push(bits.map(b => b ? 1 : 0).join(''));
    console.log(`ch${String(n).padStart(3)} ${WORLDS[w].name.padEnd(10)} "${def.name}"  speed=${def.speed} width=${def.map[0].length} frames=${bits.length} taps=${taps}`);
  }
}

const banner =
`// HUNDO chapters - generated by tools/generate.mjs, do not edit by hand.
// Every chapter here was PROVEN beatable: the generator searches the real
// game simulation for a working tap sequence and rejects anything it can't
// clear itself. Regenerate with: node tools/generate.mjs
`;
writeFileSync(join(__dir, '../js/levels.js'),
  banner +
  'const LEVELS = ' + JSON.stringify(levels) + ';\n' +
  "if (typeof module !== 'undefined' && module.exports) module.exports = LEVELS;\n" +
  'else window.LEVELS = LEVELS;\n');
writeFileSync(join(__dir, 'solutions.json'), JSON.stringify(solutions));
console.log(`\nwrote ${levels.length} chapters, all machine-verified. total taps in solutions: ${totalTaps}`);
